dump_dir: tmp

environments:
  development:
    type: local
    default_target: true
    database: duple_development

  stage:
    type: heroku
    appname: duple-stage
    default_source: true

  production:
    type: heroku
    appname: duple-production
    allow_target: false
